config/routes.rb
Rails.application.routes.draw do
  # Map admin controllers
  
  scope "/#{Humpyard::config.admin_prefix}" do 
    resources :humpyard_pages, controller: 'humpyard/pages', path: "pages", only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        post :move
      end
    end
    
    resources :humpyard_elements, controller: 'humpyard/elements', path: "elements", only: [:new, :create, :edit, :update, :show, :destroy] do
      member do
        get :inline_edit
        post :move
      end
    end
    
    resources :humpyard_assets, controller: 'humpyard/assets', path: "assets", only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        get :versions
        get :list
        get :list_item
      end
    end
  end
  
  # Map "/" URL
  root to: 'humpyard/pages#show', webpath: 'index', format: 'html'
  # Map sitemap.xml
  match "/sitemap.xml" => 'humpyard/pages#sitemap', as: 'humpyard_sitemap'
  # Map robots.txt
  match "/robots.txt" => 'humpyard/pages#robots', as: 'humpyard_robots'
  # Map human readable page URLs
  if Humpyard::config.www_prefix.match /:locale/
    match "/#{Humpyard::config.www_prefix}" => 'humpyard/pages#show', webpath: 'index', constraints: { locale: Humpyard.config.locales_contraint }
    match "/#{Humpyard::config.www_prefix}*webpath.:format" => 'humpyard/pages#show', constraints: { locale: Humpyard.config.locales_contraint, format: Humpyard.config.page_formats_contraint }
    if Humpyard.config.allow_empty_page_format
      match "/#{Humpyard::config.www_prefix}*webpath" => 'humpyard/pages#show', constraints: { locale: Humpyard.config.locales_contraint }
    end
    match "/#{Humpyard::config.www_prefix}*path" => 'humpyard/errors#error404', constraints: { locale: Humpyard.config.locales_contraint }
  else
    match "/#{Humpyard::config.www_prefix}*webpath.:format" => 'humpyard/pages#show', constraints: { format: Humpyard.config.page_formats_contraint }
    if Humpyard.config.allow_empty_page_format
      match "/#{Humpyard::config.www_prefix}*webpath" => 'humpyard/pages#show'
    end
    match "/#{Humpyard::config.www_prefix}*path" => 'humpyard/errors#error404'
  end
end

app/models/humpyard/asset.rb
module Humpyard
  class Asset < ::ActiveRecord::Base
    attr_accessible :width, :height, :size, :title, :content_type
    attr_accessible :content_data, :content_data_id, :content_data_type
    
    belongs_to :content_data, polymorphic: true, dependent: :destroy  
    
    set_table_name "#{Humpyard::config.table_name_prefix}assets"
    
    delegate :url, to: :content_data
    
    def versions
      content_data.try(:versions) || {
        original: [width, height]
      }
    end
    
    def icon
      content_data.try(:icon) || generic_icon
    end
    
    def generic_icon
      return 'icons/32x32/text.png' if content_type =~ /^text/
      return 'icons/32x32/audio.png' if content_type =~ /^audio/
      return 'icons/32x32/video.png' if content_type =~ /^video/
      
      return 'icons/32x32/unknown.png'
    end
  end
end

app/models/humpyard/assets/carrierwave_asset.rb
class Humpyard::Assets::CarrierwaveAsset < ActiveRecord::Base
  attr_accessible :file

  acts_as_humpyard_asset system_asset: true
  
  mount_uploader :file, Humpyard::AssetUploader

  def url(version = :original)
    file.url(version.try(:to_sym) == :original ? nil : version)
  end
  
  def versions options = {}
    return {original: nil} unless asset.width.to_i > 0 and asset.height.to_i > 0
    
    res = {
      original: [asset.width, asset.height],
      icon: [32, 32]
    }
    
    Humpyard::config.asset_carrierwave_image_versions.each do |k,v|
      dest_width = v[1]
      dest_height = v[2]
      scale_method = v.first.to_sym
      
      if scale_method == :fill
        res[k.to_sym] = [dest_width, dest_height]
      elsif [:fit, :limit].include? scale_method
        scale = [dest_width.to_f / asset.width,  dest_height.to_f / asset.height].min
        
        if scale > 1 and scale_method == :limit
          if options[:include_duplicates]
            res[k.to_sym] = [asset.width, asset.height]
          end
        else
          res[k.to_sym] = [(scale * asset.width).round, (scale * asset.height).round]
        end
      end
    end
    
    return res
  end
  
  def icon
    url(:icon) if versions[:icon]
  end
  
  def image_size_of(version)
    versions(include_duplicates: true)[version.try(:to_sym)] || [asset.width, asset.height]
  end
end

app/models/humpyard/assets/paperclip_asset.rb
module Humpyard
  module Assets
    class PaperclipAsset < ::ActiveRecord::Base
      attr_accessible :media
    
      acts_as_humpyard_asset system_asset: true
    
      # ToDo render styles - not working for non-images like mp3
    
      begin
        has_attached_file(
          :media, 
          default_style: :original,
          #styles: {preview: ['500x500>', :jpg], thumb: ['200x100>', :jpg]},
          path: ":rails_root/public/system/media/:id/:basename.:extension",
          url: "/system/media/:id/:basename.:extension"
        )
        validates_attachment_presence :media
        after_post_process :update_media_dimensions
      rescue
        puts "Paperclip not usable."
      end
    
      def asset_name
        media_file_name
      end
    
      def url
        media.url
      end
      
      def content_type
        media_content_type
      end
    
      def update_media_dimensions
        begin
          size = Paperclip::Geometry.from_file media.queued_for_write[:original]
          asset.width = size.width.to_i
          asset.height = size.height.to_i
        rescue
          asset.width = nil
          asset.height = nil
        end
      end
    end
  end
end

app/models/humpyard/assets/youtube_asset.rb
module Humpyard
  module Assets
    class YoutubeAsset < ::ActiveRecord::Base
      attr_accessible :youtube_video_id
    
      acts_as_humpyard_asset system_asset: true
    
      validates_presence_of :youtube_video_id
      before_save :update_youtube_data
      
      def url(version = 'original')
        "http://www.youtube.com/watch?v=#{youtube_video_id}"
      end
      
      def icon
        'icons/32x32/youtube.png'
      end
      
      def update_youtube_data      
        begin
          require 'net/http'

          xml = Net::HTTP.get_response(URI.parse("http://gdata.youtube.com/feeds/api/videos/#{youtube_video_id}")).body
          self.youtube_title = xml.force_encoding("UTF-8").scan(/<title.*>(.+?)<\/title>/).first.first
        rescue
          # Set to some sane default values if YouTube is not available
          self.youtube_title = "YouTube #{youtube_video_id}"
        end
        
        # As YouTube does not offer Video dimensions, always set to 480x360 (default thumbnail size)
        self.asset.update_attributes width: 480, height: 360, title: youtube_title, content_type: 'video/youtube'
      end
    end
  end
end

app/controllers/hump_yard/pages_controller.rb
module HumpYard
  class PagesController < ApplicationController 
    #self.template_root = File.join(File.dirname(__FILE__), '..', 'views')

    def index
  
    end

    def new
      render :text=>'test'
    end
    
    def show
      @page = nil
      if params[:id]
        @page = Page.find(params[:id])
      elsif params[:name]
        @page = Page.find_by_name(params[:name])
      end

      if params[:parent] and @page
        parent = @page.parent
        if params[:parent].class == Array
          params[:parent].reverse.each do |p|
            @page = nil if parent.nil? or parent.name != p
            parent = parent.parent unless parent.nil?
          end
        else
          @page = nil if parent.name != params[:parent]
        end
        @page = nil unless parent.nil?
      end

      render('404', :status => 404) if @page.nil?      
    end
  end
end

app/controllers/humpyard/assets_controller.rb
module Humpyard
  class AssetsController < ::ApplicationController
    rescue_from ::CanCan::AccessDenied do |exception|
      render json: {
        status: :failed
      }, status: 403
      return
    end
    
    rescue_from ::ActiveRecord::RecordNotFound, ::ActionController::RoutingError do |exception|
      render json: {
        status: :failed
      }, status: 404
      return
    end
    
    def index
      @assets = Humpyard::Asset.all
      
      authorize! :manage, Humpyard::Asset
      
      render partial: 'index'
    end
    
    def new     
      raise ::ActionController::RoutingError, 'Asset type not found' if Humpyard::config.asset_types[params[:type]].blank?
      
      @asset = Humpyard::config.asset_types[params[:type]].new()
      
      authorize! :create, @asset.asset 
      
      @asset_type = params[:type]
      
      render partial: 'edit'
    end
    
    def create  
      raise ::ActionController::RoutingError, 'Asset type not found' if Humpyard::config.asset_types[params[:type]].blank?
      
      @asset = Humpyard::config.asset_types[params[:type]].new params[:asset]
            
      authorize! :create, @asset.asset 
          
      if @asset.save
        render json: {
          status: :ok,
          replace: [{
            element: "hy-asset-listview",
            url: list_humpyard_asset_path(@asset.id)
          }],
          flash: {
            level: 'info',
            content: I18n.t('humpyard_form.flashes.create_success', model: Humpyard::Asset.model_name.human)
          }
        }
      else
        render json: {
          status: :failed, 
          errors: @asset.errors,
          flash: {
            level: 'error',
            content: I18n.t('humpyard_form.flashes.create_fail', model: Humpyard::Asset.model_name.human)
          }
        }
      end
    end
    
    def edit
      raw_asset = Humpyard::Asset.find(params[:id])
      
      authorize! :update, raw_asset
      
      @asset = raw_asset.content_data
      
      render partial: 'edit'
    end
    
    def update
      @asset = Humpyard::Asset.find(params[:id])

      authorize! :update, @asset

      if @asset.content_data.update_attributes params[:asset]
        render json: {
          status: :ok,
          replace: [
            { 
              element: "hy-asset-listview-text-#{@asset.id}",
              url: list_item_humpyard_asset_path(@asset.id)
            }
          ],
          flash: {
            level: 'info',
            content: I18n.t('humpyard_form.flashes.update_success', model: Humpyard::Asset.model_name.human)
          }
        }
      else
        render json: {
          status: :failed, 
          errors: @asset.content_data.errors,
          flash: {
            level: 'error',
            content: I18n.t('humpyard_form.flashes.update_fail', model: Humpyard::Asset.model_name.human)
          }
        }
      end
    end
    
    def show
      raw_asset = Humpyard::Asset.find(params[:id])
      
      authorize! :show, raw_asset
      
      @asset = raw_asset.content_data
      
      render partial: 'show'
    end
    
    def destroy
      @asset = Humpyard::Asset.find(params[:id])
      
      authorize! :destroy, @asset  
      
      @asset.destroy
    end
    
    def versions
      asset = Humpyard::Asset.find(params[:id])
      
      authorize! :show, asset
      
      render json: {status: :ok, versions: asset.versions.map{|k,v| v ? ["#{k.to_s.camelcase} (#{v * 'x'})", k.to_s] : ['','']}}
    end
    
    def list
      @asset = Humpyard::Asset.find(params[:id])
      @assets = Humpyard::Asset.scoped
            
      authorize! :create, @asset
      
      render partial: "list.html", locals: {assets: @assets, asset: @asset}
    end
    
    def list_item
      @asset = Humpyard::Asset.find(params[:id])

      authorize! :update, @asset
      
      render partial:'list_item.html', locals: {asset: @asset, active: true}
    end
  end
end

app/controllers/humpyard/elements_controller.rb
module Humpyard
  ####
  # Humpyard::ElementController is the controller for editing your elements
  class ElementsController < ::ApplicationController
    
    rescue_from ::CanCan::AccessDenied do |exception|
      render json: {
        status: :failed
      }, status: 403
      return
    end
    
    rescue_from ::ActiveRecord::RecordNotFound, ::ActionController::RoutingError do |exception|
      render json: {
        status: :failed
      }, status: 404
      return
    end
    
    # Dialog content for a new element
    def new
      raise ::ActionController::RoutingError, 'Element type not found' if Humpyard::config.element_types[params[:type]].blank?
      
      @element = Humpyard::config.element_types[params[:type]].new(
        page_id: params[:page_id], 
        container_id: params[:container_id].to_i > 0 ? params[:container_id].to_i : nil,
        page_yield_name: params[:yield_name].blank? ? 'main' : params[:yield_name],
        shared_state: 0)
      
      authorize! :create, @element.element 
      
      @element_type = params[:type]
      @prev = Humpyard::Element.find_by_id(params[:prev_id].to_i)
      @next = Humpyard::Element.find_by_id(params[:next_id].to_i)
      
      render partial: 'edit'
    end
    
    # Create a new element
    def create
      raise ::ActionController::RoutingError, 'Element type not found' if Humpyard::config.element_types[params[:type]].blank?
      
      @element = Humpyard::config.element_types[params[:type]].new params[:element]
      @page = @element.page
            
      authorize! :create, @element.element
            
      if @element.save
        @prev = Humpyard::Element.find_by_id(params[:prev_id])
        @next = Humpyard::Element.find_by_id(params[:next_id])
        
        do_move(@element, @prev, @next)
      
        insert_options = {
          element: "hy-id-#{@element.element.id}",
          url: humpyard_element_path(@element.element),
          parent: @element.container ? "hy-id-#{@element.container.id}" : "hy-content-#{@element.page_yield_name}"
        }
        
        insert_options[:before] = "hy-id-#{@next.id}" if @next
        insert_options[:after] = "hy-id-#{@prev.id}" if not @next and @prev
      
        render json: {
          status: :ok,
          dialog: :close,
          insert: [insert_options]
        }
      else
        render json: {
          status: :failed, 
          errors: @element.errors
        }
      end
    end
    
    # Inline edit content for an existing element
    def inline_edit
      raw_element = Humpyard::Element.find(params[:id])
      
      authorize! :update, raw_element
      
      @element = raw_element.content_data
      
      render partial: 'inline_edit'
    end

    # Dialog content for an existing element
    def edit
      raw_element = Humpyard::Element.find(params[:id])
      
      authorize! :update, raw_element
      
      @element = raw_element.content_data
      
      render partial: 'edit'
    end
    
    # Update an existing element
    def update
      @element = Humpyard::Element.find(params[:id])  
    
      authorize! :update, @element
      
      if @element.content_data.update_attributes params[:element]
        render json: {
          status: :ok,
          dialog: :close,
          replace: [
            { 
              element: "hy-id-#{@element.id}",
              url: humpyard_element_path(@element)
            }
          ]
        }
      else
        render json: {
          status: :failed, 
          errors: @element.content_data.errors
        }
      end
    end

    
    # Move an element
    def move
      @element = Humpyard::Element.find(params[:id])
            
      authorize! :update, @element
      
      @element.update_attributes(
        container: Humpyard::Element.find_by_id(params[:container_id]),
        container_slot: params[:container_slot],
        page_yield_name: params[:yield_name]
      )
      @prev = Humpyard::Element.find_by_id(params[:prev_id])
      @next = Humpyard::Element.find_by_id(params[:next_id])
      
      do_move(@element, @prev, @next)
      
      render json: {
        status: :ok
      }
    end
    
    # Destroy an element
    def destroy      
      @element = Humpyard::Element.find(params[:id])
      
      authorize! :destroy, @element  
      
      @element.destroy
    end
        
    # Render a given element
    def show
      @element = Humpyard::Element.find(params[:id])
      
      authorize! :show, @element  
      
      render partial: 'show', locals: {element: @element}
    end
    
    private
    def do_move(element, prev_element, next_element) #:nodoc#
      if element.container
        neighbours = element.container.elements
      else
        neighbours = element.page.root_elements(element.page_yield_name)
      end
      
      #p "before #{next_id} and after #{prev_id}"
      p "page_yield: #{element.page_yield_name}"

      position = 0
      neighbours.each do |el|    
        if next_element == el
          p "insert element #{element.id} before #{el.id}"
          element.update_attribute :position, position
          position += 1
        end  
        if element != el
          p "process #{el.id} to position #{position}"
          el.update_attribute :position, position unless element.position == position 
        end
        if not next_element and prev_element == el
          p "insert element #{element.id} after #{el.id}"
          position += 1
          element.update_attribute :position, position
        end
        if element != el
          position += 1
        end
      end
    end  
  end
end

app/views/humpyard/assets/_edit.html.haml
= humpyard_form_for @asset, as: :asset, url: url_for(controller: :'humpyard/assets', action: @asset.persisted? ? :update : :create), :html=>{:'data-dialog-remote' => true, :'data-dialog-form'=>'true', :'data-form-object-class' => "asset", class: 'asset-form'} do |form|
  - unless @asset.persisted? 
    = hidden_field_tag :type, @asset_type
  .dialog-search
    = "#{I18n.t("humpyard_form.titles.#{form.form_type.downcase}", model: "#{Humpyard::Asset.model_name.human}#{@asset.title.blank? ? '' : " '#{@asset.title}'"}")}"
  .dialog-pane
    .flashes
    .humpyard-tabview
      - custom_partial_path = "/humpyard/assets/#{@asset.class.name.underscore.pluralize.gsub(/^humpyard\/assets/, '')}/edit"
      - if lookup_context.exists? custom_partial_path , nil, true
        = render partial: custom_partial_path, locals: {asset: @asset, form: form}
  .dialog-buttons.humpyard-form-buttons
    = form.submit
    - if @asset.persisted? and can? :destroy, @asset.asset
      = link_to "#{I18n.t("humpyard_form.actions.destroy", model: "#{Humpyard::Asset.model_name.human}#{@asset.title.blank? ? '' : " '#{@asset.title}'"}")}", humpyard_asset_path(@asset.asset), :'data-icon' => "ui-icon-trash", confirm: "Are you sure?", method: :delete, remote: true

app/views/humpyard/assets/_index.html.haml
.humpyard-dialog-title
  = I18n.t 'humpyard_form.titles.index', model: Humpyard::Asset.model_name.human
.dialog-columns
  .left-dialog-column.with-toolbar
    .dialog-list
      #hy-asset-listview
        = render 'list', assets: @assets, asset: @asset
      #humpyard-asset-types-menu.dialog-menu
        - if can? :new, Humpyard::Asset
          - Humpyard::config.asset_types.each do |name, type|
            = link_to I18n.t('humpyard_form.actions.new', model: type.model_name.human), new_humpyard_asset_path(type: name), :'data-dialog-link' => true
    .dialog-buttons.humpyard-form-buttons     
      %a{:'data-icon' => "ui-icon-circle-plus", :'data-dialog-menu' => '#humpyard-asset-types-menu'} 
        = I18n.t('humpyard_cms.pages.edit.add', page_type: Humpyard::Page.model_name.human)
  .right-dialog-column.with-toolbar.with-search
      
    .dialog-buttons.humpyard-form-buttons
      
    - if @asset
      = render partial: 'show', locals: {page: @page}
    - else
      .dialog-pane
        Nothing selected
.humpyard-dialog-buttons

app/views/humpyard/assets/_list.html.haml
%ul
  - @assets.each do |asset|
    %li.asset{id: "hy-asset-listview-text-#{asset.id}"}
      = render 'list_item.html', asset: asset, active: (@asset and @asset==asset)

app/views/humpyard/assets/_list_item.html.haml
= link_to asset, :'data-dialog-link' => true, class: (active ? 'active' : ''), id: "hy-asset-listview-link-#{asset.id}" do
  = image_tag asset.icon, width: 32, height: 32
  %span= asset.content_data.title
  %small
    = asset.content_type
    - if asset.width
      = "– #{asset.width} x #{asset.height}"

app/views/humpyard/assets/_show.html.haml
.dialog-search
  = "#{I18n.t("humpyard_form.titles.show", model: "#{Humpyard::Asset.model_name.human}#{@asset.title.blank? ? '' : " '#{@asset.title}'"}")}"
.dialog-pane
  %table.data_table
    %tr
      %td
        = Humpyard::Asset.human_attribute_name :content_type
      %td
        = @asset.content_type
    - unless @asset.width.blank?
      %tr
        %td
          = Humpyard::Asset.human_attribute_name :width
        %td
          = @asset.width
    - unless @asset.height.blank?
      %tr
        %td
          = Humpyard::Asset.human_attribute_name :height
        %td
          = @asset.height
    - unless @asset.size.blank?
      %tr
        %td
          = Humpyard::Assets::CarrierwaveAsset.human_attribute_name :size
        %td
          = number_to_human_size @asset.size
    %tr
      %td
        = Humpyard::Asset.human_attribute_name :url
      %td
        = number_to_human_size @asset.url
    - custom_partial_path = "/humpyard/assets/#{@asset.class.name.underscore.pluralize.gsub(/^humpyard\/assets/, '')}/info_asset"
    - if lookup_context.exists? custom_partial_path , nil, true
      = render partial: custom_partial_path, locals: {asset: @asset}
  = render partial: "/humpyard/assets/show_asset", locals: {asset: @asset, element: nil}

  
.dialog-buttons.humpyard-form-buttons
  - if can? :destroy, @asset.asset
    = link_to "#{I18n.t("humpyard_form.actions.destroy", model: "#{Humpyard::Asset.model_name.human}#{@asset.title.blank? ? '' : " '#{@asset.title}'"}")}", humpyard_asset_path(@asset.asset), :'data-icon' => "ui-icon-trash", confirm: "Are you sure?", method: :delete, remote: true
  - if can? :update, @asset.asset
    = link_to "#{I18n.t("humpyard_form.actions.edit", model: "#{Humpyard::Asset.model_name.human}#{@asset.title.blank? ? '' : " '#{@asset.title}'"}")}", edit_humpyard_asset_path(@asset.asset), :'data-icon' => "ui-icon-pencil", :'data-dialog-link' => true

app/views/humpyard/assets/_show_asset.html.haml
- custom_partial_path = "/humpyard/assets/#{asset.class.name.underscore.pluralize.gsub(/^humpyard\/assets/, '')}/show"
- if lookup_context.exists? custom_partial_path , nil, true
  = render partial: custom_partial_path, locals: {asset: asset, element: element}

app/views/humpyard/assets/destroy.js.erb
remove_element('#hy-asset-listview-text-<%=@asset.id%>');
replace_content_for_element('#assets-dialog .right-dialog-column .dialog-pane', '<p><%= escape_javascript "#{I18n.t("humpyard_form.flashes.destroy_success", :model => "#{Humpyard::Asset.model_name.human}#{@asset.title.blank? ? '' : " '#{@asset.title}'"}")}" %></p>');
remove_element('#assets-dialog .right-dialog-column .dialog-buttons a');
remove_element('#assets-dialog .right-dialog-column .dialog-buttons button');